### ISSUE TITLE
Complex division by zero

### ISSUE THREAD

**Issue by EU1KY** [mihtjel/nanovna-saver#158]
**Describe the bug**

Traceback (most recent call last):
  File "nanovna-saver\NanoVNASaver\Chart.py", line 688, in paintEvent
    self.drawValues(qp)
  File "nanovna-saver\NanoVNASaver\Chart.py", line 2833, in drawValues
    imp = d.impedance()
  File "nanovna-saver\NanoVNASaver\RFTools.py", line 130, in impedance
    return gamma_to_impedance(self.z, ref_impedance)
  File "nanovna-saver\NanoVNASaver\RFTools.py", line 90, in gamma_to_impedance
    return ((-gamma - 1) / (gamma - 1)) * ref_impedance
ZeroDivisionError: complex division by zero

**To Reproduce**

Open any .s1p file in "# MHz S RI R 50" format, where at least one point has gamma of real 1.0 and imaginary 0.0, e.g.

```
# MHz S RI R 50
28.000000 0.0 0.0
28.100000 1.0 0.0
```

**Comment by zarath** [comment]
Fixed in development branch
